apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-busybox
  template:
    metadata:
      labels:
        app: my-busybox
    spec:
      containers:
      - name: busybox
        image: argocd-kubectl:latest
        command: ["sh", "-c", "kubectl && sleep 3600"]
